### ISSUE TITLE
Feature Request: Allow date formats in folder names

### ISSUE THREAD

**Issue by deathau** [liamcain/obsidian-periodic-notes#1]
I'm revamping how I do my daily notes (again) and considering using this plugin in conjunction with the [Folder Note](https://github.com/xpgo/obsidian-folder-note-plugin) plugin to create hierarchical folders like the following:
- 01 journal/
    - YYYY/
        - MM/
            - MM.md
            - ww/
                - ww.md
                - DD.md
(This structure isn't final, but also is only provided as an example, anyway)

When I attempt to add a `/` character into the format to try and create this structure (for example, a daily note format of `YYYY/MM/ww/DD` it will tell me that I've used an invalid character. Indeed, if it _did_ accept the character, it would probably fail because it's not making the folders.

So my request is to either specifically cater for the `/` in the format and create all the intermediate folders or otherwise allow formatting in the 'Note Folder' option (which also caters for creating intermediate folders)

**Comment by liamcain** [comment]
Can you screenshot your settings? That actually should work out of the box. It supports the dates as folder names + it should create the intermediate folders automatically.

Also, the error message doesn't actually block you from trying the settings out. So let me know what happens after running "Open Weekly Note" for example.

---

Small gotcha - I haven't actually released the version of the calendar that supports Periodic Notes just yet. Should have it wrapped up soon though.

**Comment by deathau** [comment]
Ah, that gotcha is probably what I'm seeing then.
Indeed it did show an error, but let me type it out and saved regardless, I just couldn't see it working because I was clicking on calendar links. Opening via the command palette works fine. Feel free to close.
![image](https://user-images.githubusercontent.com/1421840/107316599-14947880-6aed-11eb-8ef3-9ba3ddc011e0.png)

**Comment by liamcain** [comment]
> (side note: I do realize putting week notes into month folders is going to cause issues with duplicate week notes, but that's my problem)

Haha I am just curious what layout you settle on, I'm curious.

> Indeed it did show an error, but let me type it out and saved regardless, I just couldn't see it working because I was clicking on calendar links. Opening via the command palette works fine. Feel free to close.

Oh, whoops!! I'm flagging [ and ] as illegal characters. That's what the error is about. I'll make a fix 😅

**Comment by deathau** [comment]
If I just ran off a 13 month calendar, I'd be fine 😆 

Thanks for looking into the issue

**Comment by liamcain** [comment]
So, one more gotcha - the calendar plugin will need the file basename to be universally unique in order to find the correct note. That's to be compatible with people who have arbitrary folder nesting in their vaults. Instead of using `DD.md` you should use still use `YYYY-MM-DD.md` for now.

Not sure if there's a better way to support both workflows. If you have any ideas lmk!

**Comment by deathau** [comment]
I was considering doing that anyway, but thanks for the heads up on that. Saves me figuring it out the hard way later.

**Comment by liamcain** [comment]
Okay, fixed the validation errors in v0.0.4. Should be good now
