### ISSUE TITLE
just today on reddit

### ISSUE THREAD

**Issue by lwb52** [liamcain/obsidian-periodic-notes#10]
v.0.11.0—2 of us posted that yesterday’s Daily Note had disappeared…

**Comment by liamcain** [comment]
We investigated the reports of data loss and found the offending plugins. They have since been updated. Periodic Notes wasn't responsible for the issues reported. I'm going to close this issue.

**Comment by lwb52** [comment]
Thanks—I had no idea what the real source was, so I just notified all the most relevant authors I could think of…
