### ISSUE TITLE
what happens if more than one note matches the date

### ISSUE THREAD

**Issue by pcause** [liamcain/obsidian-periodic-notes#102]
One thing that isn't at all clear is what happens if more than one note matches the date.  One could have a note that has the date in the front matter and a note with date in the name.  What will occur?

**Comment by liamcain** [comment]
Hi! Good call, I should make this more clear in the documentation.

The plugin will find all matches and classify them with the following criteria:
- **Is Exact Match** - Does the filename match the format exactly. This helps differentiate between `2022-04-14.md` and `2022-04-14 meeting notes.md`. If the date is found in the frontmatter, this also counts as an exact match
- **Match Type** - A match type is either `filename`, `date-prefixed`, or `frontmatter`.

When opening a note for a particular day, the algorithm always looks for **exact** matches and it prefers frontmatter matches over filename matches.

So if you have a `2022-04-14.md` and a file that contains `day: 2022-04-14`, it will return the file with the frontmatter match.

**Protip**: If you are using the Date Switcher to find a date note, you can press <kbd>Tab</kbd> to show all the inexact matches.

Hope that clears things up!

**Comment by pcause** [comment]
Yes, definitely does and what I thought but thought I'd ask because I knew it would prompt you to update the docs.

BTW, what would be very nice would be a way to offer to create a note that uses embeds to have all the content in a single note or merges the content of the matched pages.  Even a simple concatenation would make this incredibly powerful.

**Comment by liamcain** [comment]
Oooh, I like that idea a lot! A kind of unified view of your day. I give it some more thought but feel free to open a separate issue especially if you have more ideas for how you'd like it to work/behave.

**Comment by JohnKnoepfle** [comment]
Hi @liamcain, I just started using the Periodic Notes plugin, and I'm fairly new to Obsidian overall.   I've seen the mention of using the "Date Switcher" to navigate to other notes or , as mentioned above, hitting tab to show inexact matches, but I'm not sure what the Date Switcher actually is.   I don't see a date switcher in the command palette for Periodic Notes or elsewhere.

**Comment by pcause** [comment]
ctrp-p then periodic notes: show data switcher.  bind a hot key for easier access.

**Comment by liamcain** [comment]
@JohnKnoepfle, the Date Switcher is a feature available in the Beta version of Periodic Notes. You can test it out by if you have the [BRAT plugin](https://github.com/TfTHacker/obsidian42-brat) installed and add `liamcain/obsidian-periodic-notes` as a "beta plugin."

Otherwise you can wait until it's released, hopefully soon!

**Comment by JohnKnoepfle** [comment]
Thank you @liamcain!    I missed that this was a beta feature.   I assume that's also true for the Timeline Complication?   Both sound like great features so I will give the beta a try.
