### ISSUE TITLE
Calander sets not working (bug)

### ISSUE THREAD

**Issue by AdityaBanik** [liamcain/obsidian-periodic-notes#106]
I don't find an option to use calendar sets.
I installed the latest version of obsidian this is what the periodic notes settings looks like (*** no calander sets feature ***)

![image](https://user-images.githubusercontent.com/70037338/163649651-25bc286f-0077-4268-abde-1e9b76b5ed4e.png)

**Comment by liamcain** [comment]
Hi sorry, I’ve been busy getting the README ready in anticipation of the big release, I forgot to put a disclaimer. The calendar sets feature is still for beta users only. If you use the BRAT you can enable the periodic notes beta from there.

**Comment by AdityaBanik** [comment]
> Hi sorry, I’ve been busy getting the README ready in anticipation of the big release, I forgot to put a disclaimer. The calendar sets feature is still for beta users only. If you use the BRAT you can enable the periodic notes beta from there.

Thank you for your response❤️. I really appreciate your work on these plugins. 
I will try test out the feature in the beta version.
