### ISSUE TITLE
Sidebar icon to open today's note

### ISSUE THREAD

**Issue by mileyvirus** [liamcain/obsidian-periodic-notes#11]
Hey there, thanks for the awesome work. The only thing missing from the core Daily Notes plugin – for me – is the little sidebar icon to quickly open today's note.

I hope you'll consider it, thanks for the hard work!

**Comment by liamcain** [comment]
I added a Ribbon Icon to v0.0.10 for opening Today's Note. It only appears if the core Daily Note plugin is disabled (to avoid confusion). Let me know if you think it would be valuable to include one for opening the weekly and/or monthly note.

**Comment by mileyvirus** [comment]
Thank you!

> Let me know if you think it would be valuable to include one for opening the weekly and/or monthly note.

I wouldn't use those personally. I can't speak for others tho! Maybe the best way would be to have a toggle in the settings to show/hide the sidebar icon for each periodic note type.
