### ISSUE TITLE
[1.1.0] calendar: open weekly note not obey the weekly syntax format

### ISSUE THREAD

**Issue by bytemain** [liamcain/obsidian-periodic-notes#110]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13938334/164894223-5e8be4ac-d06c-4b44-9613-0b6ccfb44694.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/13938334/164894179-90c2f1fc-ba3b-44e7-a4d1-daf3c10621fb.png">

but the previous version is supported

**Comment by bytemain** [comment]
it seems that daily note also not work

<img width="595" alt="image" src="https://user-images.githubusercontent.com/13938334/164894361-3efcc596-3715-41e4-addd-c1bbaafd3534.png">

**Comment by liamcain** [comment]
Hi @bytemain, thanks for the report. This is a known issue. I'm tracking the Calendar plugin support issue here: #100 

It will be fixed in the next version of the Calendar plugin.
