### ISSUE TITLE
[1.0 feature request] contexts

### ISSUE THREAD

**Issue by pcause** [liamcain/obsidian-periodic-notes#114]
A very common feature of most todo list that came from the GTD methodology is the context.  For example: @home or @texasoffice  The idea is that a task has a project and a context within which it gets done.  Perhaps you can extend the tasks  popup to have a context entry line and add something to the task queries to also allow specifying the context.  Since a number of things (Reminders) use the @ character, allow user to specify the character or pick an emoji.  The GitHub cyclone might be one or perhaps the GitHub label.

**Comment by liamcain** [comment]
Is this request intended for a different plugin? I'm not sure it related to Periodic Notes.
