### ISSUE TITLE
[Bug][v1.0.0 beta3]fail to load plugin periodic-notes

### ISSUE THREAD

**Issue by taso998** [liamcain/obsidian-periodic-notes#115]
When I installed the periodic-notes from ob, I found there is not "calender set" in the settings, and I noticed that the version is 0.0.17 only. I guess it is because this feature was not included in such early version, so I download v1.0.0 beta3 from Github and move to the plugin folder, however, when I open ob, the enable button is gray and when I click it, it show "fail to load plugin periodc-notes". 
I tried v1.0.0 and meet the same issue. 
I doubt if there is any confliction in my settings, so I create a new & empty vault, copy the v1.0.0 beta3 to plugin folder, still meet this issue.

**Comment by taso998** [comment]
I update my ob from 0.12.16 to the latest 0.14.6, this issue has been fixed.

**Comment by Balstun** [comment]
@taso998 Hi, I'm experiencing a similar issue with defining **calender sets** as well with the _Periodic Notes_ plugin. I'm having no issues setting up daily/weekly/monthly/... notes by the "default" calender set, and can successfully enable it.
However, I'm unaware as to how to properly setup different calender sets, nor do I see such an option as defined in the documentation.

![image](https://user-images.githubusercontent.com/42073460/168486079-b541e3d6-939c-4dee-9a40-2f8292c5d8f9.png)

Please note that my **current version: v0.14.6** for Obsidian, though my installer is only v0.12.19. Why do you think the issue persists for me? Is there anything else you suggest I do regarding this matter?
