### ISSUE TITLE
[Minor bug] Duplicate tab in plugin options when toggling on/off periodic notes

### ISSUE THREAD

**Issue by bk7312** [liamcain/obsidian-periodic-notes#12]
When toggling on/off periodic notes, it creates duplicate tabs under the plugin options. See screenshot below. Duplicate tabs are removed after restarting obsidian so it's not a big deal.

![image](https://user-images.githubusercontent.com/14029543/108580640-56cc7e00-7367-11eb-9bc3-1b5a5ddd53ce.png)

**Comment by liamcain** [comment]
Good catch! Will be fixed in the next version.
