### ISSUE TITLE
Date calculation for weekly note tag

### ISSUE THREAD

**Issue by np-22** [liamcain/obsidian-periodic-notes#123]
Date calculation for weekly note tag is not working. It is mentioned in the doc that it should be supported. Wonder how I should set it up. Here is my attempt:
![[{{monday-7d:YYYY-[W]ww_MM-DD}}#Tracking]]

**Comment by fkuersch** [comment]
I assume that this feature is not released yet, see the [note in the README.md](https://github.com/liamcain/obsidian-periodic-notes/blob/main/README.md?plain=1#L7)

I used this template instead (works with Templater and is based on the file name):
https://github.com/liamcain/obsidian-periodic-notes#95#issuecomment-1096430426

**Comment by np-22** [comment]
Thanks @fkuersch! I didn't notice this disclaimer. Yeah using Templater as a workaround works!
