### ISSUE TITLE
Does the (date) switcher still exist?

### ISSUE THREAD

**Issue by fncll** [liamcain/obsidian-periodic-notes#124]
I am very confused. The docs indicate there is a date switcher command `Periodic Notes: Show date switcher...` but I do not see that command. In fact, I don't see any switcher commands?

**Comment by liamcain** [comment]
Hi, the date switcher is still only in the beta version and I plan on releasing it soon. I'll add a "coming soon" note to the features that haven't been released just quite yet. Sorry for the confusion.

**Comment by fncll** [comment]
Got it. Thank you!
