### ISSUE TITLE
Request: date math in templates

### ISSUE THREAD

**Issue by ryanjamurphy** [liamcain/obsidian-periodic-notes#16]
My use case: I have a header on my daily notes that provides a link from today to yesterday and to tomorrow. Currently I just write "yesterday" and "tomorrow" in the template, and when I first create a day's note I manually rewrite the correct date. 

It'd be great to automate this a bit more by allowing date math in templates. Something like e.g., `{{date:yyyyMMdd[-1d]}}` to subtract a day from the date it was generated for.

Thanks for all the great work! ✨

**Comment by ryanjamurphy** [comment]
Oops. On second glance, this is actually a feature request for [Daily Notes Interface](https://github.com/liamcain/obsidian-daily-notes-interface/blob/main/src/daily.ts#L33).

To brainstorm a bit:
- It looks like it'd be implemented at least in part with the [`createDailyNote`](https://github.com/liamcain/obsidian-daily-notes-interface/blob/6e8ff35a02eb2cadf14cb2a66fc9c9f8d7afb46e/src/daily.ts#L17) function (and `createWeeklyNote` and `createMonthlyNote`);
- `createDailyNote` could take in an optional string parameter of some date math syntax;
- it could then call a dateCalculation function that uses [moment's `.add` function](https://momentjs.com/docs/#/manipulating/) to do the math.

**Comment by liamcain** [comment]
For the syntax, I don't think I want to use `[-1d]` since it looks like it's supposed to be interpreted by Moment.js. What do you think of `{{ date+1d : YYYY-MM-DD }}`
