### ISSUE TITLE
No Calendar sets 

### ISSUE THREAD

**Issue by brisim-claimhte** [liamcain/obsidian-periodic-notes#170]
Just downloaded periodic notes and there are no options for calendar sets, it just has the notes options 
![image](https://user-images.githubusercontent.com/120045419/215096514-ab32bcda-9303-4763-a6e7-498bd3259fb7.png)

**Comment by dsegonds** [comment]
Calendar set is available in the 1.0.0-beta3 version.

**Comment by deurk** [comment]
(that you have to install manually from this repo)
