### ISSUE TITLE
`Open date switcher` is not listed in the Commands

### ISSUE THREAD

**Issue by romusz** [liamcain/obsidian-periodic-notes#174]
<img width="655" alt="Screenshot 2023-02-17 at 12 16 47 PM" src="https://user-images.githubusercontent.com/854559/219720301-b69d83c1-6f80-4360-8403-228df3a1e0ae.png">

**Comment by geoelectric** [comment]
There's a note on the README that @liamcain updated it for 1.0--7 months ago--with features that are vapor in the actual released version. I'm really surprised they chose to do that and leave it that way given they didn't have time to actually see the work through. I assume that's also where Calendar Sets and the Timeline Complication that doesn't exist lives.

It's going that one step further to highlight that all of these Calendar/Date related projects desperately need more hands involved...or a fork. In the meantime, not sure if the code for the 1.0 beta is actually pushed here where you could sideload it, or what.

**Comment by liamcain** [comment]
Yes, all the changes are on master, but I never cut an official release for 1.0 since I never found time to iron out some bugs. I'm restored the old README to avoid confusion. Sorry about that.

**Comment by geoelectric** [comment]
Thank you. It really did make them awfully confusing, and I’d even used Periodic Notes in the past! I think reverting them until actual release will help a lot.
