### ISSUE TITLE
Feature request: Multiple journals

### ISSUE THREAD

**Issue by pgrz** [liamcain/obsidian-periodic-notes#176]
My workflow consists of two journals (private and work-related). I'd love to be able to use the Periodic Notes for managing them both automatically.

**Comment by jeetsukumaran** [comment]
You can by using calendar sets. As of the current date, you would need to install Periodic Notes using the BRAT plugin to get this feature, as calendar sets are only available on the beta release.

**Comment by pgrz** [comment]
Thanks, I will check it out!
