### ISSUE TITLE
Documentation seems to have regressed

### ISSUE THREAD

**Issue by clearf** [liamcain/obsidian-periodic-notes#177]
The HEAD readme.md is much worse than it was about a year ago: 

see e.g., 
https://github.com/liamcain/obsidian-periodic-notes/blob/1a498919b7fd20c3f5eb2ff097c30260c8693043/README.md

**Comment by liamcain** [comment]
Yes, the README was reverted so that it reflects the currently released version instead of showing the beta details. Even with the disclaimer at the top, the README was causing confusion (see: https://github.com/liamcain/obsidian-periodic-notes/issues/174).
