### ISSUE TITLE
Link to Weekly Note from Daily Note using the template

### ISSUE THREAD

**Issue by adarsh** [liamcain/obsidian-periodic-notes#178]
(cross posted to the forum [here](https://forum.obsidian.md/t/periodic-notes-plugin-generate-filename-in-daily-notes-template-pointing-to-weekly-note/55927))

This might be a obvious question but the answer isn't making sense to me, so here goes:

How can I add something to the Daily Notes Template file which links to that week's Weekly Note?

As in:

```
(Daily Notes Template File)
# {{date:MMMM D, YYYY}} Work Journal

tags: #work_journal 

## Weekly Goals
(I want to autogenerate this preview link below, pointing to the first day of the week)
![[2023_03_05_weekly_note#Weekly Goals]]

## Today's Goals
1. text 

## Journal
- text

## Tomorrow's Priorities
1. text 
```

**Comment by SkydiveMike** [comment]
Actually I see for you original question that you maybe just want one header. TBH the code above is simplified, I actually have:

`![[<%tp.date.now("GGGG-[W]WW", 0, tp.file.title)%>#What are this week’s big three Plan for Success|Review this week’s Big Three]]`

Which transcludes a Header Section from my Weekly note into my Daily Note.

**Comment by adarsh** [comment]
Thanks! I have tried this in my daily notes template `, which looks like this:

```
![[<%tp.date.now("GGGG-[W]WW", 0, tp.file.title)%>#Weekly Goals]]
```

And this is the result (this file does exist and is called `2023_03_12_weekly_note`:
![image](https://user-images.githubusercontent.com/913757/226129643-9372fc9a-60c4-4a76-90de-6189adceecce.png)

Any suggestions?

**Comment by SkydiveMike** [comment]
Do you have JavaScript queries enabled?
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/119014/229379177-9cf6be03-c46d-45cd-bf10-bbb487fbe6ab.png">

**Comment by SkydiveMike** [comment]
Did you enable Templater? It looks like the template code `<% … %>` is not being executed.

**Comment by adarsh** [comment]
I figured it out. 

I needed to enable "Settings > Templater > Trigger Template on new file creation". 

At which point this gave me what I wanted:
```
![[<% tp.date.weekday("YYYY_MM_DD", 0) %>_weekly_note#Weekly Goals]]
```
which generated

```
![[2023_05_21_weekly_note#Weekly Goals]]
```

My guess is there are two templating actions (with different formats) happening in Periodic Notes:
1. The Periodic Notes plugin templating replacements (e.g. `{{date:YYYY-MM-DD}}` format)
2. The Templater plugin replacements, (e.g. `<% tp.date.weekday... %>`) which won't kick in when using Periodic Notes unless you enable the above trigger

So with the Templater trigger set, I can mix them both in my daily notes template file:
```
# {{date:MMMM D, YYYY}} Work Journal

tags: #work_journal  

![[<% tp.date.weekday("YYYY_MM_DD", 0) %>_weekly_note#Weekly Goals]]

## Daily Goals
1. 

## Journal
- text

## Tomorrow's Priorities
1. text 

## Todo List Log
```
