### ISSUE TITLE
Time doesn't work when using date:

### ISSUE THREAD

**Issue by Amparose** [liamcain/obsidian-periodic-notes#18]
If I have {{date:HH:mm}} in my template, Periodic notes resolves that to 00:00 when creating a new note.

- Inserting the same template into a blank note works,
- Using the default Daily notes core plugin works,
- Using `{{time}}` works in Periodic notes.

**Comment by liamcain** [comment]
Great catch, will fix this for the next release!

**Comment by liamcain** [comment]
Great catch, this should be resolved now in v0.0.10.
