### ISSUE TITLE
Blank page in the periodic notes interface

### ISSUE THREAD

**Issue by wenlzhang** [liamcain/obsidian-periodic-notes#2]
I updated to the latest version of the periodic notes and calendar plugins and clicked to migrate daily and weekly notes settings. After doing this, the periodic notes setting interface becomes blank.

I tried to re-install it and re-start Obsidian, and it did not change anything.

**Comment by liamcain** [comment]
Uh oh, sorry about that. I knew I shouldn't have done such a late night release 😓 .

There should be an error message in the Dev Tools console that will help me debug. Could you open the Dev Tools (control+shift+i on Windows, command+shift+i on macOS) the go to the Console Tab. There should be an error there. Could you send me a screenshot of that?

![image](https://user-images.githubusercontent.com/693981/107362772-32d78580-6aa7-11eb-8d34-bc3bf5eaea0f.png)

**Comment by wenlzhang** [comment]
Thanks for the hard work and quick reply. 😄

I first re-started Obsidian, and once I click Periodic Notes in the plugin managing pane, I got the following error message:
![image](https://user-images.githubusercontent.com/44930227/107365540-3ab21c80-6add-11eb-9584-ccd792591b12.png)

**Comment by liamcain** [comment]
Thanks for the screenshot. It helped narrow down what was happening.

I released a new version of the plugin with a fix for the issue (version 0.0.5). You can update the plugin from within settings. Let me know if the issue persists!
