### ISSUE TITLE
Open daily note and templater don't go well together

### ISSUE THREAD

**Issue by ruben-sg** [liamcain/obsidian-periodic-notes#205]
I have a template for my daily note that has links to yesterday's and tomorrow's daily note in the header. I used templater like this:

[[<% tp.date.yesterday("YYYY-MM-DD") %>|< gestern]] | [[<% tp.date.tomorrow("YYYY-MM-DD") %>| morgen >]]

If I insert the template on a note, it works fine. If I use "Open daily note", it doesn't do anything. Why is that? What am I missing?

**Comment by iurimatias** [comment]
@ruben-sg in Templater, you need to enable this

![Screenshot 2024-01-03 at 10 09 09 AM](https://github.com/liamcain/obsidian-periodic-notes/assets/176720/e4f59eb7-ff2d-49b9-9a0a-f7b900092903)

**Comment by ruben-sg** [comment]
Didn't see that. Thank you!
