### ISSUE TITLE
Quarterly, annually, septimesally reviewing

### ISSUE THREAD

**Issue by josephholsten** [liamcain/obsidian-periodic-notes#23]
I’ve got notes for quarter and annum of my work’s fiscal year. It’s fussy and obnoxious. So I figure it’s the perfect edge case to see it’s in scope!

My company’s fiscal year schedule looks like:
FY22 begins 2021-06-01 ends 2025-05-31
FY22Q1 begins 2021-06-01 ends 2021-08-31

Of course, my personal chronicles use gregorian years and quarters beginning at solstices and equinoxes.

Some day I’ll probably lose it and switch to a lunar calendar and want to do my reviews every seven phases of the moon (septimesal!)

Do any of these sound remotely reasonable?

**Comment by topperge** [comment]
I'll second the request for Quarterly Notes. This would be extremely helpful for planning and methodologies like best year ever.

**Comment by zenodotus280** [comment]
I support this. @josephholsten How do you break up the year? I do 4*13 starting with ISO Week 1.

**Comment by JeppeKlitgaard** [comment]
I would also love to see both quarterly and annual notes.

I had actually completely forgotten that periodic notes and calendar weren't part of Obsidian Core - they integrate so seamlessly!

**Comment by liamcain** [comment]
I have plans to include this soon. Since there are a few similar feature requests to this one, I created a separate ticket to track the feature and will close this in favor of #98 which includes a rough outline of what I'm planning.
