### ISSUE TITLE
Variables for note folder names

### ISSUE THREAD

**Issue by RichSteele** [liamcain/obsidian-periodic-notes#25]
It would be useful to be able to use variables in the folder names so that my journal directory doesn't get so large over time. For example, I could have a directory structure like [journal]/YYYY/W so that end up with a week's worth of notes in a directory together.

**Comment by liamcain** [comment]
Hi @RichSteele, you can already accomplish this by using the "Format" field:

For example: if you set the format to `[journal]/YYYY/YYYY-[W]ww` it will create the folders that you need.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/693981/111852801-c1cd8e00-88ee-11eb-9542-b7d840239037.png">

Let me know if that works for your use case.

**Comment by RichSteele** [comment]
That works of course. I'd tried to set a pattern in the folder setting but didn't think to try in the format. It might be helpful to others to mention in the help text for that field to mention that you can use / as a directory separator in the syntax.

Thanks!

**Comment by welpdx** [comment]
> Hi @RichSteele, you can already accomplish this by using the "Format" field:
> 
> For example: if you set the format to `[journal]/YYYY/YYYY-[W]ww` it will create the folders that you need.
> 
> <img alt="image" width="945" src="https://user-images.githubusercontent.com/693981/111852801-c1cd8e00-88ee-11eb-9542-b7d840239037.png">
> 
> Let me know if that works for your use case.

Wow, this is really good to know. I actually was planning to start a discussion here about the same thing lol. Looks like RichSteele beat me to it. Thanks @liamcain and @RichSteele

**Comment by Elizabethcase** [comment]
on this note -- I have folders named, e.g. 10October. MMMMMM renders as October10. Any thoughts on how to use variable names but get around the auto ordering?
