### ISSUE TITLE
Which icon should I click if I just want to activate Weekly / Month note?

### ISSUE THREAD

**Issue by desktopofsamuel** [liamcain/obsidian-periodic-notes#28]
## Current Behavior

Weekly & monthly note is only accessible by command, while daily note can be accessible by clicking the Calendar Icon on the left icon bar.

## Possible Solution

Not sure if there are plans on supporting this but personally I only use Monthly & Weekly notes only, it would be great if 
- there are other icons made for day / week / month?  OR
- when user click on the icon, there is a modal asking what kind of periodic note do you want to create? I've created a quick mockup for reference

![Obsidian-Feedback](https://user-images.githubusercontent.com/35249407/112337013-84a33a80-8cf8-11eb-8d43-fae97c3041bb.png)

**Comment by liamcain** [comment]
Hi @desktopofsamuel

😍 This modal is a great idea! I love the mock-up. You're right that the plugin is missing a better way to open weekly and monthly notes. I didn't like the idea of having 3 ribbon icons so this feels like a nice improvement.

For weekly notes currently, you can at least click on the week numbers if you have this enabled in the Calendar plugin settings -
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/693981/112486291-2145f680-8d52-11eb-93c3-44367c3961af.png">

I also will be adding a button to the Calendar for monthly notes in an upcoming update.

But I think this proposal fills a nice gap, especially for users that don't have a need for the calendar plugin.

**Comment by liamcain** [comment]
Hi @desktopofsamuel, I hope you don't mind, I ended up using your modal design for the final result:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/693981/113152931-9a3ac780-9204-11eb-8946-71c0913e1cd3.png">

I would love to credit you in the README if you're okay with that.

**Comment by desktopofsamuel** [comment]
Looks very nice!! Yes, feel free to credit in README, happy to help! @liamcain
