### ISSUE TITLE
Suggestions don't update when filling out the monthly note template field

### ISSUE THREAD

**Issue by argenos** [liamcain/obsidian-periodic-notes#3]
When typing in the monthly template text box, the suggestions won't auto-update: 

![Peek 2021-02-09 18-49](https://user-images.githubusercontent.com/5426039/107405392-8ed1f680-6b07-11eb-855a-c92ec9ecb4a4.gif)

## Additional information
Obsidian version: v0.10.13
OS: Ubuntu 18.04
Portable notes: v0.0.6
Calendar: v1.5.0

**Comment by liamcain** [comment]
Aha! Thanks for the gif. Turns out it doesn't work if you use uppercase letters.  Will have a fix soon.
