### ISSUE TITLE
[Feature] Sidebar ribbon button - allow for restoring old behaviour of opening only today note

### ISSUE THREAD

**Issue by danieltomasz** [liamcain/obsidian-periodic-notes#35]
While more choice is always good forcing users to choose which note to open may break their workflows.
The 2-clicks and hoovering mouse is more  friction than 1-click as it was before. 

Proposition
Add toggle in Periodic notes setting that will decide about Ribbon button action
- If the user want to open today daily note  or want the new menu with an option to choose

An example of how this might be implemented in settings is a Devonlink plugin
https://github.com/ryanjamurphy/DEVONlink-obsidian
![image](https://user-images.githubusercontent.com/7980381/113280902-35a36980-92e5-11eb-8046-194d29c6bdc6.png)

Alternatives:
User will use  Obsidian default today note plugin to open today note
Possible problems with this approach:
-  it will duplicate the setup of today note
- Icons for both plugins are the same 

Obsidian 0.11.9
Plugin Verison 0.0.13

**Comment by liamcain** [comment]
Hi @danieltomasz, you raised a great point. I gave this some thought and came up with a compromise. The new behavior is that clicking the icon will open the daily note (matching the old behavior). However, I also added a right-click menu to the ribbon icon for opening weekly and monthly notes. This avoids introducing a new configuration option, exposes all the same functionality, and keeps the UI lightweight. (The downside right now is feature discovery, which I plan to improve)

I am still debating if the modal is necessary or if this covers all use cases.

**Comment by danieltomasz** [comment]
Nice idea! About discoverability concerns, would one time info screen would help (it will display something only when user first time click button)

**Comment by liamcain** [comment]
I was thinking of just adding something similar to the Photoshop toolbar - a small triangle to indicate that there's more options within.

<img width="103" alt="image" src="https://user-images.githubusercontent.com/693981/113336108-de58c580-92f3-11eb-8889-531988af902e.png">

But a one-time tooltip could work!

**Comment by sirnails** [comment]
> I also added a right-click menu to the ribbon icon for opening weekly and monthly notes.

How do I reach weekly and monthly on mobile?
