### ISSUE TITLE
Open Note in a new Pane (from Ribbon)

### ISSUE THREAD

**Issue by jtmusky** [liamcain/obsidian-periodic-notes#40]
Opening a daily note from the calendar (via mouse) or the hotkey, it replaces the current note. Please add the ability to open in a new pane.

Thanks for considering
-JM

**Comment by liamcain** [comment]
This is already possible via the calendar if you click on a day while holding down <kbd>Command</kbd> on MacOS or <kbd>Control</kbd> on Windows.

But I can add something similar to the ribbon button. Good idea!

**Comment by jtmusky** [comment]
Oh, I didn't know you could hold down `cmd/ctrl` and open to a new pane from the cal, thought it was for previewing. If this was in the documentation, I didn't read it. 😁

**Comment by jtmusky** [comment]
So intuitively. I tried `cmd/ctrl` clicking on the "TODAY" link on the calendar. Thought it would open today's note in a new pane. Should I write up a new feature request?

**Comment by liamcain** [comment]
`cmd/ctrl` clicking on things to open in a new pane is standard across obsidian. It should work in search, file explorer, and from the quick switcher.  So I think it makes sense to add it to the ribbon icon for Periodic Notes too. 

As for the TODAY button specifically, I plan on keeping the existing functionality and switching out the next for an icon to avoid the confusion.

**Comment by liamcain** [comment]
This was added in v0.0.16
