### ISSUE TITLE
No Daily Note Created if File Found in Sub-folder

### ISSUE THREAD

**Issue by ddetton** [liamcain/obsidian-periodic-notes#46]
I use the Calendar and Periodic Notes plugins with the core Daily Note plug in disabled.  I created a sub-folder called _Calendar under my _DailyNotes folder for storing my calendar events for the day.  When I create the calendar event file (using iCal Buddy) I name the file the same as my daily note file (YYYY-MM-DD.md) and store it in the/_DailyNotes/_Calendar folder.  The Calendar event file gets created before the Daily Notes file.  When I click on Open Daily Note in Obsidian, it does not create the daily note but it does open the calendar event file even though that file is not in the _DailyNotes folder, it is in the /_DailyNotes/_Calendar folder.  My daily note template includes a link to the calendar event file.  I have included screen shots of my Periodic Notes parameters and my file system folders that show that today's daily note does not exist.  As a workaround, I could make the _Calendar folder at the same level as the _DailyNotes folder, but I would rather keep it subordinate.  Thanks.

![Capture3](https://user-images.githubusercontent.com/3335359/115426024-fdd96480-a1b4-11eb-9498-1c28ebae25d6.PNG)

![Capture2](https://user-images.githubusercontent.com/3335359/115426003-f87c1a00-a1b4-11eb-9997-0eabdc31adb7.PNG)

![Capture1](https://user-images.githubusercontent.com/3335359/115425973-f2863900-a1b4-11eb-9b3e-9ac098dc8d72.PNG)

**Comment by liamcain** [comment]
Is there any reason the formats need to match for `_DailyNotes` and `_Calendar`? Could you just format the `_Calendar` notes as `[Events]-YYYY-MM-DD` instead to avoid confusing the parser? I don't have a better solution for you right now since the behavior you're seeing is by design to allow more flexible folder structures.

**Comment by ddetton** [comment]
Thats a good idea.  Thanks Liam!
