### ISSUE TITLE
Next/Prev Weekly Note Command Not Working

### ISSUE THREAD

**Issue by JamesAndrewsCoulter** [liamcain/obsidian-periodic-notes#49]
Unable to move forward and back between weekly notes using the command, however can for daily just fine. Also, when I try to navigate to the current weekly note, a notification reads 'Unable to create new file'

See folder structure: 
<img width="170" alt="image" src="https://user-images.githubusercontent.com/83034789/116230662-35698300-a758-11eb-91d4-80b885acfaf7.png">

Weekly Note Template:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/83034789/116230728-4b774380-a758-11eb-9e9d-b08480255080.png">

Plugin Configuration:
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/83034789/116230786-5af68c80-a758-11eb-8cc0-ba7d4eb1a721.png">

**Comment by liamcain** [comment]
Hi @JamesAndrewsCoulter, in your weekly note format, you have `yyyyww`. The `yyyy` isn't [actually a valid parsing token](https://momentjs.com/docs/#/displaying/format/) (I'm surprised that it parses it at all). What you want here instead is `ggggww` and it should work as expected.

I'll make a note to show an error message by the format input in the future.

**Comment by JamesAndrewsCoulter** [comment]
Works like a charm! Thank you for the quick and friendly troubleshooting.
