### ISSUE TITLE
"Format contains illegal characters" when using emojis and possibly other allowed symbols.

### ISSUE THREAD

**Issue by AlansCodeLog** [liamcain/obsidian-periodic-notes#5]
Not a huge issue. Everything still works though if you ignore it. Reason I ran into this is my template is `YYYY-MM📅` so they're easier to find in the graph view.

I pinned the issue down to this line. https://github.com/liamcain/obsidian-periodic-notes/blob/a1f85d0b99708f7982ee8cf9e0c88aad181b12c7/src/settings/validation.ts#L10

The regex is too strict. I would suggest using a regex that matches anything but obsidian's current prohibited characters `/^[^*"\\/<>:|?]+$/` although this might still be too strict in the future due to this request probably getting implemented soon: https://forum.obsidian.md/t/list-of-not-allowed-characters-in-the-file-name-make-it-os-specific

Alternatively, error when the user tries to create the note?

**Comment by liamcain** [comment]
Good call, that validation is definitely too strict. I'll revisit it for the next version, thanks for flagging!

**Comment by liamcain** [comment]
This is now be fixed in version 0.0.8. Let me know if you're still experiencing issues!
