### ISSUE TITLE
Creating a periodic note does not run variables through community Templater

### ISSUE THREAD

**Issue by uwidev** [liamcain/obsidian-periodic-notes#61]
I use the community Templater plugin to run javascript code for variable templates depending on what day it is. For example, I would have the following within my template: `<%* tR += moment.weekdays()[new Date().getDay()] %>`.  When this template is inserted, today's weekday will be returned.

When opening today's note, the plugin loads the template without parsing any delimiters for variables. Is this intended?

**Comment by bigredjoe** [comment]
You can get it to work by enabling this setting in Templater:
![image](https://user-images.githubusercontent.com/145475/150684962-676fdcc7-3876-4fc4-839f-e8f9447bed94.png)
