### ISSUE TITLE
Open Next [Week|Day] Doesn't Create New File

### ISSUE THREAD

**Issue by KyleKing** [liamcain/obsidian-periodic-notes#69]
To replicate behavior I was seeing in my customized plugin, I created an new, empty test vault, installed only periodic-notes and default settings, then create a note for today and this week

When trying to select either "Periodic Notes: Open next weekly note" (or "... next daily note"), nothing happens. Should the plugin be creating the new file?

**Comment by adamyonk** [comment]
I would like this to work that way too!

**Comment by notflip** [comment]
Is this a something that has been requested before? I just came here to request this feature! That if the next day doesn't exist, the plugin would create the file, I might have a look to see if I can create a PR

**Comment by KyleKing** [comment]
Giving this some additional thought, I like how the implementation cycles through only created entries and prefer the current behavior. If there is a gap, I don't want a bunch of days to be created when going forward or backward through the entries. 

If I really need to create an entry for tomorrow, I've added links to my template and can click to create a new file (although it may take some manual movement to place it in the right directory):

```md
## Footer

- Yesterday: [[Day<% tp.date.now("DDD-ddd_DDMMMY", -1) %>]]
- Tomorrow: [[Day<% tp.date.now("DDD-ddd_DDMMMY", 1) %>]]
```

I'm going to go ahead and close this issue. If implemented, I imagine it might be a new shortcut to create a file if not found
