### ISSUE TITLE
Missing Periodic Notes Folder

### ISSUE THREAD

**Issue by Mallysj** [liamcain/obsidian-periodic-notes#74]
I have a folder for all my periodic notes and sometimes, when I start or restart obsidian, this folder disappears. I have to restart my laptop just so I can see the folder again. Please help, thank you so much.

**Comment by eXpl0it3r** [comment]
Which folder are you referring to?
Where your notes (daily/weekly/yearly) are located? Or the one in the .obsidian/plugins directory? Or something else?

Do you use Obsidian Sync or some other cloud service?
What version of Obsidian are you using and on with OS?

**Comment by Mallysj** [comment]
Hello! All of my periodic notes are stored in my main vault, in a folder I named "10 Dated". It contains my daily, weekly, and monthly notes--all of which are made using the periodic notes plug-in.

I use Obsidian Git. I am using the V0.12.19 version of Obsidian with Windows 10.

If it matters, I recently moved my files from a laptop (which was very slow) to a computer. While I do not need to restart my device anymore to view the "10 Dated" folder in obsidian, the said folder still disappears from time to time though now a simple restart of the app "fixes" it.

Thank you so much for your time.

**Comment by eXpl0it3r** [comment]
That sounds much more like an Obsidian issue, than anything related to Periodic Notes. The plugin itself doesn't, as far as I know, deal with how notes are loaded into Obsidian.
Maybe you can find similar issues on the Obsidian forum or find more help on the Obsidian Discord.
