### ISSUE TITLE
(optional) Navigation Icon for Weekly / Monthly notes

### ISSUE THREAD

**Issue by eXpl0it3r** [liamcain/obsidian-periodic-notes#76]
Currently there's the "Open Today" icon on the side bar (maybe driven by the core plugin?).
As I want to use weekly notes more often, it would be great to enable an "Open Week" button as well.

**Comment by liamcain** [comment]
Hi @eXpl0it3r, you can right-click on the `Open Today` button to see the other options. Sorry it's not super discoverable, but I didn't want to take up too much room in the app ribbon.

**Comment by eXpl0it3r** [comment]
Oh, that's neat! Maybe a note somewhere in the readme would help with the discoverability. 🙂
