### ISSUE TITLE
"Unable to create file" error when using ISO week "gggg-[W]WW" 

### ISSUE THREAD

**Issue by mturilin** [liamcain/obsidian-periodic-notes#79]
<img width="1098" alt="Screen Shot 2021-11-29 at 5 13 20 PM" src="https://user-images.githubusercontent.com/843131/143967765-19f52581-ea01-407a-99e7-46bf6c0801d2.png">

- I set up my weekly file pattern to "gggg-[W]WW" 
- When I click on "Open this week" button I see an error "Unable to create file"

**Root cause:**
I dug through the source code. The problem that when the app calculates the beginning of the week we should use:
- ISO week: moment.startOf("isoWeek")
- Normal week: moment.startOf("week")

**Test case:**

```
> window.moment("2021-W47", "gggg-[W]WW", true).startOf("week").format("gggg-[W]WW");
< "2021-W46" // ERROR: expected "2021-W47"

> window.moment("2021-W47", "gggg-[W]WW", true).startOf("isoWeek").format("gggg-[W]WW");
< "2021-W47" // SUCCESS - this is what we should use for ISO weeks

> window.moment("2021-W47", "gggg-[W]ww", true).startOf("week").format("gggg-[W]ww");
< "2021-W47" // Non-ISO week works fine

```

**Comment by liamcain** [comment]
Yeah, this plugin admittedly could handle ISO dates better. Thanks for the report and the debugging!

A workaround for now is to change your locale using the Calendar plugin. In the Calendar plugin settings, there's a dropdown to change the locale to `en-GB` which will get respected by Periodic Notes too. Then can keep the format as `gggg-[W]ww` which will be the same as the ISO week numbers.

But I'll work on getting a real fix in soon!

**Comment by WhiteNoiseDev** [comment]
@mturilin shouldn't you use GGGG-[W]WW for complete ISO format? (there may be a difference at the end of the year)

**Comment by jkrcma** [comment]
Btw using `GGGG-[w]WW` instead (or without the square brackets `GGGG-WW`) does work, but such format generates `2021-w52` (or without `w`) for the current week, which is also wrong.

**Comment by willgraham345** [comment]
I'm also having this issue. I've tried to use the solution from @jkrcma, but I haven't had any luck. Has there been any progress in solving this bug? I've screenshotted my configuration to help debug :)

![image](https://github.com/liamcain/obsidian-periodic-notes/assets/49169367/6a861ec7-5972-43d2-a33d-79bb171424ea)
