### ISSUE TITLE
Weekly Notes not recognized

### ISSUE THREAD

**Issue by welpdx** [liamcain/obsidian-periodic-notes#8]
After the weekly notes are created, Periodic Notes does not recognize it and wants to create another weekly note. 

See gifs below:
Error produced in a nested folder.
![error](https://i.imgur.com/kvBMC3I.gif)
Error reproduced in a test folder at root of the vault. 
![error](https://i.imgur.com/koIsLZZ.gif)

Periodic Notes Version: 0.0.8

I appreciate your help.

**Comment by liamcain** [comment]
Hi @welpdx, thanks for the detailed bug report. I was able to replicate the issue and put in a fix for both periodic notes and the calendar plugin.

Let me know if you're still running into any issues!

**Comment by welpdx** [comment]
Wow thanks for the quick fix Liam!
The update fixed the problem for me. It's all good! XD
