### ISSUE TITLE
Feature Request: General Note option

### ISSUE THREAD

**Issue by jimpfaff** [liamcain/obsidian-periodic-notes#80]
I love this Obsidian Plugin. It's great. And I am using it to great benefit. There is something I'd like to recommend you add which would benefit me and might others as well. Would it be possible to create an option in the settings that would create a general note of the person's choosing as another option beyond the Daily, Weekly, Quarterly, and Yearly notes? For me, this would allow the creation of a planning note into a specified folder which would supplement my organization approach. For me in particular, I have goal templates which sometimes have date specificity to them. clicking on the Calendar and having them available as another option would be great. I'm asking because it seems a simple code fix by just adding another section to the settings with all the same options. And allowing the naming option to be more customizable than the mere date would be great.

I think I may find (or may create myself at some future date) another workaround to this. Or I'll take some time maybe to update your code myself. But I also don't like to clutter customizable apps like Obsidian with too many plugins. Thanks for your consideration

**Comment by liamcain** [comment]
I have plans to include this soon. Since there are a few similar feature requests to this one, I created a separate ticket to track the feature and will close this in favor of #98
