### ISSUE TITLE
Calendar pane has disappeared

### ISSUE THREAD

**Issue by pdworkman** [liamcain/obsidian-periodic-notes#81]
I was able to use Periodic Notes on Sunday without a problem. Today when I went in to make a change, I could not get the calendar to appear. I have disabled and re-enabled, closed and reopened the vault, etc. but no luck. It still tells me that the plug-in that created the pane is no longer active.

**Comment by liamcain** [comment]
Hi @pdworkman, the calendar is a separate plugin from Periodic Notes. If you have the Calendar plugin installed though, double check that the right sidebar isn't collapsed.

There is a command called "Toggle right sidebar," so first check if the pane is just hidden.

![image](https://user-images.githubusercontent.com/693981/147678909-c102f420-7796-4546-8e01-c9bb2980f421.png)

If the sidebar is showing and there's still no calendar, can you search in the command palette for `Calendar: Open View`

![image](https://user-images.githubusercontent.com/693981/147679145-e9fc167d-8a2c-42c6-82af-b37ce20a8231.png)

That command will only appear if you accidentally closed the calendar.

---

Let me know if any of that fixes your issue!

**Comment by pdworkman** [comment]
I have resolved.

Calendar: Open View did not show up in the command palette.

I went to the plugins and Calendar was disabled. I tried to enable it, and got the message that it could not be enabled. I removed the plugin, then reinstalled it. Calendar could then be toggled on. I still did not get the Calendar: Open View command in the command palette. I did get the little "go to today" icon on the left side, which would open my today note, but still didn't show the calendar in the right sidebar.

I closed the vault and reopened it, and then got the calendar tab in the right sidebar.

Now working! 

I am not sure what might have triggered this problem. 
1. Live Preview came out this weekend, and I did turn it on for part of Sunday, then found that Advanced Tables didn't work and disabled it.
2. I started using Sync to synchronize this vault on Sunday.

**Comment by liamcain** [comment]
I don't think the Live Preview release would have affected it but maybe Sync caused it to get disabled. Glad to hear you have it working though!

>  I tried to enable it, and got the message that it could not be enabled. I removed the plugin, then reinstalled it

This is a little concerning though, I wonder if you ran into a bug that caused it to get disabled instead. It will be hard to debug unless you had a copy of the error logs though.
