### ISSUE TITLE
Next weekly note command not working

### ISSUE THREAD

**Issue by usmanity** [liamcain/obsidian-periodic-notes#85]
I just started using the plugin so my settings/understanding could be wrong but this is what I'm observing:

1. Open command palette for "Open weekly note" and it takes me to the current week's note.
2. If I open the command palette again and go to "Next weekly note" it doesn't go anywhere, this is while I'm on the current week's note.

I made sure to try this from other place, from an unrelated note (not a periodic note), as expected, I don't see the "Next weekly note" command available. But I'm not sure why "Next weekly note" command does not work from current week's note. 

I can provide any info if needed.

**Comment by rzfzr** [comment]
"Unable to create new file." right?

**Comment by AtrumGeost** [comment]
Hi @usmanity !

Not sure if the same happened to you. I thought I had the same issue you described here. Using the  "Next weekly note" command wasn't doing anything. Then I realized this command is for _navigation only_, meaning it won't create a new weekly note. However, the command will work if you already have the next/previous weekly notes created already.

**Comment by usmanity** [comment]
Yup! I didn't realize it was only for navigation! I thought it was creation too. Thanks. I'll close this ticket then.
