### ISSUE TITLE
Show Monday's todos on Friday

### ISSUE THREAD

**Issue by pcause** [liamcain/obsidian-periodic-notes#89]
In my daily template I have the following to show the days and next days tasks

** TODAY or TOMORROW**
```tasks
not done
due before in 2 days OR start today
due after yesterday
sort by due
hide task count
```

On Friday I'd like to also show Monday's due tasks.  I don't think there is a way to do this, is there?  I tried:

due before in 2 weekdays OR start today

but it didn't work.  momentjs has a function for weekdays so thought it might.  is this possible?

**Comment by liamcain** [comment]
Hi, I think you may have posted this issue on the wrong plugin repo. This plugin doesn't do anything related to tasks.
