### ISSUE TITLE
Note Creation Formatting not working on Mobile

### ISSUE THREAD

**Issue by heph3astus** [liamcain/obsidian-periodic-notes#90]
When running the create periodic note commands (for any time scale), it names the folder "YYYY" instead of the actual year, and does this same thing in the title of the note. This does not occur on desktop for me, but does on mobile

**Comment by jacksteamdev** [comment]
@heph3astus This works for me on mobile, do you still encounter this problem?

**Comment by heph3astus** [comment]
I forgot to close this. It fixed itself in one of the recent updates.
