### ISSUE TITLE
Weekly Notes - Unable to create a new file. 

### ISSUE THREAD

**Issue by x4IPx** [liamcain/obsidian-periodic-notes#94]
Hi, everybody 
Today is the seventh week. In the "Weekly Notes" setting, in the "Format" field, set the value "gggg-[W]WW". But when trying to create it, it writes me an error: Unable to create a new file. 
I ask for help in fixing the problem .

Expected output : 2022-[W]07

![image](https://user-images.githubusercontent.com/58852253/154250280-93620b57-fecf-440d-bd8e-5fd3f4dbd734.png)

**Comment by datavistics** [comment]
Do you have that file already created?

**Comment by x4IPx** [comment]
No. It wasn't.
But the 2022-W08 week was created successfully. Right now I don't see any errors. 
I have suspicions that the error was related to file system access rights. 
Thanks for the answer!

**Comment by lukeabbott** [comment]
I am experiencing the same issue. The format GGGG-[W]WW is returning 2022-W07, it should be returning 2022-W08. ISO 8601 says it is week 8. WW should return ISO week.

The file does already exist, because 2022-W07 is last week. But Periodic notes is checking for 2022-W08 to exist, it doesn't exist yet so Periodic notes attempts to create 2022-W07 and fails.

**Comment by x4IPx** [comment]
The problem persisted.
What I noticed today:
Today 02/28/2022, when using the prefix gggg-[W]WW , the file 2022-W08 is created despite the preview 2022-W09 :
![image](https://user-images.githubusercontent.com/58852253/155975768-0be2949e-c319-4cac-a97e-6902dc5a6fc7.png)

**Comment by liamcain** [comment]
Thanks for this report. I see what the issue is and it will be fixed in the next update. Sorry for taking so long to address this.

**Comment by x4IPx** [comment]
Thank you! I am glad

**Comment by x4IPx** [comment]
Thank you! I am glad
