### ISSUE TITLE
Template date math is undocumented

### ISSUE THREAD

**Issue by colintedford** [liamcain/obsidian-periodic-notes#96]
I use Periodic Notes's date math template tags, but when I tried to tell someone about them I couldn't find anything about it in the documentation. I guess I learned it from the Obsidian forums, but it should be documented.

**Comment by jacksteamdev** [comment]
@colintedford Not exactly math, but there's this: https://github.com/liamcain/obsidian-periodic-notes#weekly-template-tags

Can you provide some examples here?

**Comment by liamcain** [comment]
@colintedford Good point! It should be documented. I'll add something to the README.

**Comment by liamcain** [comment]
Added some basic documentation here: https://github.com/liamcain/obsidian-periodic-notes#date-calculations.

Thanks again for bringing to my attention!
